# ============================================================
# Konfigurasi Moodle (config.php + moodledata)
# ============================================================

param(
    [string]$MoodleDir  = "C:\MoodleKelas\laragon\www\moodle",
    [string]$MoodleData = "C:\MoodleKelas\moodledata",
    [string]$DbName     = "moodle_lokal",
    [string]$DbUser     = "moodle_user",
    [string]$DbPassword = "MoodleKelas2024!",
    [string]$LocalPort  = "8080"
)

if (-not (Test-Path $MoodleDir)) {
    throw "Moodle tidak ditemukan di $MoodleDir"
}

# ─── Buat config.php ────────────────────────────────────────
$wwwroot = if ($LocalPort -eq "80") {
    "http://localhost/moodle"
} else {
    "http://localhost:$LocalPort/moodle"
}

$configPhp = @"
<?php  // Moodle configuration file - generated by MoodleKelas Installer

unset(`$CFG);
global `$CFG;
`$CFG = new stdClass();

`$CFG->dbtype    = 'mysqli';
`$CFG->dblibrary = 'native';
`$CFG->dbhost    = 'localhost';
`$CFG->dbname    = '$DbName';
`$CFG->dbuser    = '$DbUser';
`$CFG->dbpass    = '$DbPassword';
`$CFG->prefix    = 'mdl_';
`$CFG->dboptions = array(
    'dbpersist' => 0,
    'dbport'    => 3306,
    'dbsocket'  => '',
    'dbcollation' => 'utf8mb4_unicode_ci',
);

`$CFG->wwwroot   = '$wwwroot';
`$CFG->dataroot  = '$($MoodleData -replace '\\', '/')';
`$CFG->admin     = 'admin';
`$CFG->directorypermissions = 02777;

// Performance settings untuk LAN
`$CFG->cachetype     = 'file';
`$CFG->sessioncookiepath = '/';

require_once(__DIR__ . '/lib/setup.php');
"@

Set-Content -Path "$MoodleDir\config.php" -Value $configPhp -Encoding UTF8
Write-Host "  config.php dibuat: $MoodleDir\config.php"

# ─── Permissions moodledata ─────────────────────────────────
if (-not (Test-Path $MoodleData)) {
    New-Item -ItemType Directory -Path $MoodleData | Out-Null
}

# Set ACL agar web server bisa write
$acl = Get-Acl $MoodleData
$rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "BUILTIN\IIS_IUSRS", "FullControl",
    "ContainerInherit,ObjectInherit", "None", "Allow")
try { $acl.AddAccessRule($rule); Set-Acl $MoodleData $acl } catch {}

# Juga untuk Everyone (Laragon/Nginx)
$rule2 = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "Everyone", "FullControl",
    "ContainerInherit,ObjectInherit", "None", "Allow")
try { $acl.AddAccessRule($rule2); Set-Acl $MoodleData $acl } catch {}

Write-Host "  moodledata permissions diset: $MoodleData"
Write-Host "  Moodle wwwroot: $wwwroot"
